version: '3.8'
services:
  app:
    build: .
    container_name: smart-res-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - MONGO_URL=mongodb://mongo:27019/smart-resident
      - JWT_SECRET=your_jwt_secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27015:27015"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
  redis_data:
